export {
  BROADCAST_DISCOVERY_TICK_MS,
  BROADCAST_HEARTBEAT_TTL_MS,
  BROADCAST_PACKET_LOSS_BLOCK_PERCENT,
  BROADCAST_PREFERRED_CAMERA_COUNT,
  BROADCAST_SNAPSHOT_POLL_MS,
  BROADCAST_STORAGE_WARNING_GB,
  isBroadcastDevMode,
} from "@/services/broadcast/config";
