/** @deprecated Import from `@/lib/features/auth/tenant-auth-assets` instead. */
export {
  TENANT_AUTH_ASSET_VERSION as AWAKENING_AUTH_ASSET_VERSION,
  TENANT_AUTH_LOGIN_ART as AWAKENING_AUTH_LOGIN_ART,
  TENANT_AUTH_SIGNUP_ART as AWAKENING_AUTH_SIGNUP_ART,
  TENANT_AUTH_NATIVE as AWAKENING_AUTH_NATIVE,
  TENANT_AUTH_ASSETS as AWAKENING_AUTH_ASSETS,
  TENANT_AUTH_LOGIN_COMPONENTS as AWAKENING_AUTH_LOGIN_COMPONENTS,
  tenantAuthAssetUrl as awakeningAuthAssetUrl,
  TENANT_AUTH_LOGIN_FORM as AWAKENING_AUTH_LOGIN_FORM,
  TENANT_AUTH_LOGIN_HEADER_HEIGHT as AWAKENING_AUTH_LOGIN_HEADER_HEIGHT,
  TENANT_AUTH_LOGIN_PANELS as AWAKENING_AUTH_LOGIN_PANELS,
  TENANT_AUTH_SIGNUP_PANELS as AWAKENING_AUTH_SIGNUP_PANELS,
  type AuthLoginComponentKey,
  type AuthLayoutRect,
} from "@/lib/features/auth/tenant-auth-assets";
