/** @deprecated Import from `@/lib/features/dashboard/tenant-dashboard-assets` instead. */
export {
  TENANT_DASHBOARD_ARTBOARD as AWAKENING_DASHBOARD_ARTBOARD,
  TENANT_DASHBOARD_CONCERT_BACKDROP_ART as AWAKENING_CONCERT_BACKDROP_ART,
  TENANT_DASHBOARD_MOBILE_VIEWPORT as AWAKENING_MOBILE_DASHBOARD_VIEWPORT,
  TENANT_DASHBOARD_CONTAINER as AWAKENING_DASHBOARD_CONTAINER,
  TENANT_DASHBOARD_BUTTON_GRID_SCALE as AWAKENING_DASHBOARD_BUTTON_GRID_SCALE,
  TENANT_DASHBOARD_OVERLAY_LAYOUT as AWAKENING_DASHBOARD_OVERLAY_LAYOUT,
  TENANT_DASHBOARD_STORY_TOP_Y as AWAKENING_DASHBOARD_STORY_TOP_Y,
  TENANT_DASHBOARD_CREATOR_STREAM_SRC as AWAKENING_CREATOR_STREAM_SRC,
  TENANT_DASHBOARD_ASSETS as AWAKENING_ASSETS,
  TENANT_DASHBOARD_BUTTON_ASSETS as AWAKENING_DASHBOARD_BUTTON_ASSETS,
  TENANT_DASHBOARD_BUTTON_GRID as AWAKENING_DASHBOARD_BUTTON_GRID,
  TENANT_DASHBOARD_CARDS as AWAKENING_DASHBOARD_CARDS,
  TENANT_DASHBOARD_CARDS_MOBILE as AWAKENING_DASHBOARD_CARDS_MOBILE,
  TENANT_DASHBOARD_PRELOAD_ASSETS as AWAKENING_PRELOAD_ASSETS,
} from "@/lib/features/dashboard/tenant-dashboard-assets";
