import type { Incident } from "@/lib/incidents/types";

function atToday(hour: number, minute: number, second = 0): string {
  const date = new Date();
  date.setHours(hour, minute, second, 0);
  return date.toISOString();
}

function atDaysAgo(days: number, hour: number, minute: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc-001",
    time: atToday(19, 21, 34),
    user: "producer@300a.com",
    action: "CONFIG_UPDATE",
    target: "Countdown start time to 7:30 PM",
    severity: "info",
    status: "open",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-ops-01",
    description: "Countdown schedule updated for tonight's broadcast window.",
    payload: { field: "countdown_start", value: "19:30", timezone: "America/New_York" },
    snapshots: ["/snapshots/countdown-config-001.png"],
  },
  {
    id: "inc-002",
    time: atToday(19, 15, 2),
    user: "vmix_ops@300a.com",
    action: "INGEST_RECONNECT",
    target: "Reconnected after 2.1s drop",
    severity: "warning",
    status: "open",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-ffmpeg-02",
    description: "Primary RTMP ingest dropped briefly and recovered automatically.",
    payload: { dropMs: 2100, lane: "primary", recovered: true },
    snapshots: ["/snapshots/ingest-reconnect-002.png"],
  },
  {
    id: "inc-003",
    time: atToday(19, 10, 11),
    user: "producer@300a.com",
    action: "GO_LIVE_ATTEMPT",
    target: "Pre-flight interlock blocked",
    severity: "warning",
    status: "open",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-ops-01",
    description: "Go-live blocked until readiness score cleared producer review threshold.",
    payload: { readinessScore: 78, required: 80, blocked: true },
    snapshots: [],
  },
  {
    id: "inc-004",
    time: atToday(19, 5, 45),
    user: "system@300a.com",
    action: "AUDIO_ALERT",
    target: "Audio levels below threshold",
    severity: "critical",
    status: "open",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-ffmpeg-02",
    description: "Master audio bus dropped below -42 dB for more than 5 seconds.",
    payload: { masterDb: -44.2, thresholdDb: -42, durationSec: 5.4 },
    snapshots: ["/snapshots/audio-meter-004.png"],
  },
  {
    id: "inc-005",
    time: atToday(18, 59, 17),
    user: "media@300a.com",
    action: "CAMERA_SWITCH",
    target: "Switched to Stage camera",
    severity: "info",
    status: "reviewed",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-ops-03",
    description: "Program bus switched from wide to stage camera for rehearsal.",
    payload: { from: "cam-wide", to: "cam-stage" },
    snapshots: ["/snapshots/camera-stage-005.png"],
  },
  {
    id: "inc-006",
    time: atToday(18, 50, 33),
    user: "system@300a.com",
    action: "BACKUP_STREAM",
    target: "Backup stream connection good",
    severity: "info",
    status: "open",
    streamId: "stream-backup-001",
    tenantId: "300-awakening",
    workerId: "worker-ffmpeg-04",
    description: "Backup HLS lane validated and marked healthy.",
    payload: { lane: "backup", latencyMs: 820, healthy: true },
    snapshots: [],
  },
  {
    id: "inc-007",
    time: atToday(18, 42, 8),
    user: "admin@300a.com",
    action: "WORKER_RESTART",
    target: "FFmpeg worker pool node restarted",
    severity: "warning",
    status: "escalated",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-ffmpeg-02",
    description: "Worker ffmpeg-02 restarted after elevated CPU for 90 seconds.",
    payload: { cpuPercent: 91, restartReason: "cpu_threshold" },
    snapshots: ["/snapshots/worker-restart-007.png"],
  },
  {
    id: "inc-008",
    time: atToday(18, 30, 55),
    user: "vmix_ops@300a.com",
    action: "DESTINATION_FAILURE",
    target: "YouTube RTMP destination unreachable",
    severity: "critical",
    status: "open",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-dest-01",
    description: "YouTube destination failed connection test during pre-show validation.",
    payload: { destination: "youtube", error: "connection_timeout", retryCount: 2 },
    snapshots: ["/snapshots/dest-youtube-008.png"],
  },
  {
    id: "inc-009",
    time: atToday(18, 18, 22),
    user: "producer@300a.com",
    action: "RECORDING_STARTED",
    target: "ISO recording armed for main program",
    severity: "info",
    status: "open",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-record-01",
    description: "Main program ISO recording armed ahead of countdown.",
    payload: { format: "mp4", storage: "s3", profile: "1080p60" },
    snapshots: [],
  },
  {
    id: "inc-010",
    time: atDaysAgo(0, 17, 55),
    user: "system@300a.com",
    action: "CHAT_MODERATION_ALERT",
    target: "Spike in flagged chat messages",
    severity: "warning",
    status: "open",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-chat-01",
    description: "Moderation queue exceeded 12 flagged messages in 60 seconds.",
    payload: { flaggedCount: 14, windowSec: 60 },
    snapshots: [],
  },
  {
    id: "inc-011",
    time: atDaysAgo(1, 20, 12),
    user: "producer@300a.com",
    action: "PRESHOW_CHECK_FAILED",
    target: "Destination validation incomplete",
    severity: "warning",
    status: "resolved",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-ops-01",
    description: "Pre-show automation halted on missing backup destination URL.",
    payload: { step: "destination_validation", passed: false },
    snapshots: ["/snapshots/preshow-fail-011.png"],
  },
  {
    id: "inc-012",
    time: atDaysAgo(2, 19, 44),
    user: "vmix_ops@300a.com",
    action: "BITRATE_DROP",
    target: "Encoder bitrate fell below 2.5 Mbps",
    severity: "critical",
    status: "reviewed",
    streamId: "stream-main-001",
    tenantId: "300-awakening",
    workerId: "worker-ffmpeg-02",
    description: "Program encoder reported sustained bitrate drop during rehearsal.",
    payload: { bitrateMbps: 2.1, targetMbps: 3.25, durationSec: 18 },
    snapshots: ["/snapshots/bitrate-drop-012.png"],
  },
];

export function cloneMockIncidents(): Incident[] {
  return MOCK_INCIDENTS.map((incident) => ({
    ...incident,
    payload: { ...incident.payload },
    snapshots: [...incident.snapshots],
  }));
}
